### ISSUE TITLE
dummyapi.io does not work

### ISSUE THREAD

**Issue by archieby** [PacktPublishing/Vue.js-3-for-Beginners#6]
dummyapi.io does not work for the "app-id": "1234567890" provided in the book, and I suppose the biggest part of the book relies on the data it provides :)
`{
    "error": "APP_ID_NOT_EXIST"
}`

SSO to the dummyapi.io service also does not work

**Comment by josefk934565** [comment]
I'm also having this problem. I can't seem to log into dummyapi with my Github or gmail accounts. It just redirects me to login in an infinite loop. I can't get an App-ID so I can't get API responses.
